<!-- About / Tramaine & Ashley -->
	<div class="w3-container w3-padding-64 usMobile" id="us" style="color:#fff;background: url(/images/map5.jpg); background-size: cover; background-position: center center; background-repeat: no-repeat; background-attachment: fixed; color: black;">
	<div class="w3-display-container w3-wide w3-margin scrollImg" style="position: relative;">
	  <div class="w3-row storyTime" style="padding: 50px 75px;">
		<h2 class="text-center w3-padding">Let me tell you how it all got started!</h2>
		<h3 class="text-center w3-padding">Pick a story</h3>
		<!--- <img src="images/flower2.png" class="valign-wrapper w3-hide-small" style="max-height:150px; position:absolute; right:0px; transform:rotate(250deg);" />
		<img src="images/flower2.png" class="valign-wrapper w3-hide-small" style="max-height:150px; position:absolute; left:0px; transform:rotate(250deg);" /> --->
		<ul class="hisAndHers">
			<li class="hers w3-half w3-xlarge w3-border w3-border-black text-center w3-hover-border-red w3-padding" onclick="myFunction('her_story')"><span><i class="fa fa-female"></i>&nbsp;Hers</span></li>
			<li class="his w3-half w3-xlarge w3-border w3-border-black w3-hover-border-blue text-center w3-padding" onclick="myFunction('his_story')"><span><i class="fa fa-male"></i>&nbsp;His</span></li>
		</ul>
		<div class="hisStory" id="his_story" style="/* background: radial-gradient(circle, transparent 89%, gray, blue); */ position:relative;">
			<div id="bgrdShadow"></div>
			<div class="" style="position:relative;">
				<i class="" style="w3-border">Our story for me starts around the same time, 2008 at Britney's house. While me and guys were driving over to Britney's house party, Kev was giving everybody the run down of who all was going to be there. He told us it was the same girls from Widener University that were always around. Once we got there, I knew everybody but Ashley and actually didn't pay much attention to her but I remembered that she was a cutie. Some time goes by and me and the guys were heading to another gathering one of Kev's friends at D&B. On our way over there, we find out it's going to be the same crew as before. Ashley didn't really seem interested in any of the guys, so we still didn't cross path's or intereact at all! Fast forward another year or so and we meet again at another gathering (our friends like to have gatherings). After being around each other on so many occassions, I figure she wasn't going anywhere so I finally decided to actually have a conversation with her. And it seemed like the conversation went on for hours, talking about everything imaginable. After that night I get a text from Kev asking if it was ok if Ashley had my phone number. I knew it was over for her from there. She had been poisoned by my stinger #scorpioSeason! From that day, we talked, and talked some more and talked a little bit more. She soon became the only person I really wanted to talk to. Then one day she comes and tells me we're in a relationship. She said it from another room because she knew it was a bold move. But I didn't put up much of a fight because when she wants something she's going to get it no matter the cost. Half a decade later, through all the ups and downs, joys and tears, I couldn't think of a better person to have by my side.</i>
			</div>
		</div>
		<div class="herStory w3-padding-large w3-margin" id="her_story" style="/* background: radial-gradient(circle, transparent 89%, gray, red); */ position:relative; text-align: justify;">
			<div id="bgrdShadow"></div>
			<div class="" style="position:relative;">
				<i>How We Met….Our Love Story! I remember first meeting Maine in the Fall of 2008 at Britney’s house; one of my Maids of Honor. She was having her first get together in her new apartment.
				Although my girls say Maine had been around before and at our dorm room a few times, this is the first time I remember actually noticing him. He was cute, and his personality drew me in. He was the life of the party and much like me; goofy, silly, and down for a good time. But I was involved in another relationship and couldn’t make a move.Fast forward three years. Although Maine and I had been in each other’s company quite a few times over the years, we both had been involved with other people. But by the Fall of 2011, things had changed. That’s when Maine really caught my attention.I remember in August of 2011 after a birthday outing with the gang, I started asking my girls if they knew his background and if he was talking to anyone in particular. When the general consensus was “No”, my little wheels began to turn.In September of 2011 at yet another birthday outing, Maine and I finally sparked up a conversation that would be the beginning to forever. In that conversation, he made me realize that my happiness was the most important thing and that, in return, my children would see that happiness and be better off. A few weeks went by and I knew I had to come up with a way to spark another conversation, but how? Not knowing when our next group outing would be, I put the thought to the side, until a coworker told me she applied for a position at DaVita. BINGO! I remembered from a conversation that Maine worked at DaVita. So I kindly asked our mutual friend Kev for Maine’s phone number and added that I wanted to see if Maine had any pull at his job. Of course I knew Kev wouldn’t want to be the middle man, and he quickly sent me Maine’s number.After an exchange of text messages back and forth about my coworker, I thanked Maine for looking out and ended the conversation. The goal was to now wait until Maine randomly texted me because he now had my number.Low and behold, I didn’t have to wait long; he fell right into the trap! lol The next morning I got a text asking how my day was going and what I was up to. We texted all day long about any and everything. I remember not texting back so fast. I didn’t want to seem to into him, but in reality I was checking my phone every five seconds to see if he had written me anything.These conversations continued over the next couple of months, through his 25th birthday, Thanksgiving, and Christmas. We routinely had long phone conversations that didn’t end until one of us fell asleep on the other.By early January of 2012 I knew he was someone special and for me. The way he made me laugh, the way he looked at me, the jokes we shared -- it was just different. Shortly after this, I looked up our zodiac signs and it said that a Taurus and Scorpio would make a powerhouse and relationship-wise were great for each other. Maine and I joked about it at the time, but we have become just that -- a powerhouse. The rest is history!</i>
			</div>
			</div>
		</div>
	  </div>
	<div class="text-center py-5 d-none d-md-block">
		<img class="m-5 mw-100" src="/images/at3.jpg">
	</div>
	</div>
	<div></div>